"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import {
  type FeatureCollection,
  type FlagProps,
  type Stats,
  DATA_URL,
  drySeasons,
  kindLabel,
  lakeUrl,
  loadFlags,
  loadStats,
  seasonLabel,
} from "@/lib/data";

type Flag = FeatureCollection<FlagProps>["features"][number];

function centroid(g: GeoJSON.Geometry): [number, number] {
  const rings =
    g.type === "Polygon" ? [g.coordinates[0]] : g.type === "MultiPolygon" ? g.coordinates.map((p) => p[0]) : [];
  const pts = rings.flat();
  if (!pts.length) return [0, 0];
  const lon = pts.reduce((a, p) => a + p[0], 0) / pts.length;
  const lat = pts.reduce((a, p) => a + p[1], 0) / pts.length;
  return [lon, lat];
}

function fill(template: string, values: Record<string, string>) {
  return template.replace(/\{\{(\w+)\}\}/g, (m, k) => values[k] ?? m);
}

function Letter({ title, text }: { title: string; text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="card" style={{ marginTop: 12 }}>
      <div className="row" style={{ justifyContent: "space-between" }}>
        <strong>{title}</strong>
        <button
          className="secondary no-print"
          onClick={() => navigator.clipboard.writeText(text).then(() => setCopied(true))}
        >
          {copied ? "Copied" : "Copy text"}
        </button>
      </div>
      <pre style={{ whiteSpace: "pre-wrap", fontFamily: "inherit", fontSize: "0.9rem" }}>{text}</pre>
    </div>
  );
}

export default function EvidenceView({ id }: { id: string }) {
  const [stats, setStats] = useState<Stats | null>(null);
  const [flags, setFlags] = useState<Flag[]>([]);
  const [templates, setTemplates] = useState<{ complaint: string; rti: string } | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([
      loadStats(id),
      loadFlags(id),
      fetch("/templates/complaint.md").then((r) => r.text()),
      fetch("/templates/rti.md").then((r) => r.text()),
    ])
      .then(([s, f, complaint, rti]) => {
        setStats(s);
        setFlags(f.features);
        setTemplates({ complaint, rti });
      })
      .catch((e) => setError(String(e)));
  }, [id]);

  if (error) return <main><p>Could not build the evidence pack: {error}</p></main>;
  if (!stats || !templates) return <main><p className="muted">Building evidence pack…</p></main>;

  const usable = drySeasons(stats).filter((s) => s.status === "ok");
  const first = usable[0];
  const last = usable.at(-1);
  const top = [...flags].sort((a, b) => b.properties.area_ac - a.properties.area_ac)[0];
  const generated = new Date().toISOString().slice(0, 10);
  const packId = `${id}-${generated}`;

  const letterValues = (f: Flag | undefined): Record<string, string> => {
    const [lon, lat] = f ? centroid(f.geometry) : [0, 0];
    return {
      lake_name: stats.name,
      flag_id: f?.properties.flag_id ?? "",
      centroid_lat: lat.toFixed(5),
      centroid_lon: lon.toFixed(5),
      area_ac: f ? f.properties.area_ac.toFixed(2) : "",
      zone: f?.properties.zone === "buffer" ? "30 m buffer" : "lakebed",
      first_seen: f ? seasonLabel(f.properties.first_seen) : "",
      status: f?.properties.status ?? "",
      confidence: f?.properties.confidence ?? "",
      scene_ids: f?.properties.scene_ids.join(", ") ?? "",
      baseline_years: "2019–2020",
      pack_id: packId,
    };
  };

  return (
    <main>
      <div className="row no-print" style={{ justifyContent: "space-between", marginBottom: 8 }}>
        <Link href={`/lake/${id}/`}>← Back to {stats.name}</Link>
        <div className="row">
          <a className="button secondary" href={lakeUrl(id, "flags.geojson")} download={`${id}-flags.geojson`}>
            Download flags (GeoJSON)
          </a>
          <button onClick={() => window.print()}>Save as PDF</button>
        </div>
      </div>

      <h1>Evidence pack: {stats.name}</h1>
      <p className="muted small">Pack {packId} · results as of {stats.as_of} · generated by KereWatch</p>
      {stats.sample && <p className="notice">Sample data, not real results. Do not file.</p>}
      <p className="notice">
        This pack reports change detected from satellite imagery against the lake&apos;s historical water extent.
        It is not a land survey and does not establish ownership or legality. Verify on the ground and in records.
      </p>

      <h2>Summary</h2>
      <table>
        <tbody>
          <tr><th>Reference lake area</th><td>{stats.reference_area_ac.toFixed(2)} acres (mapped outline + 2019–2020 water)</td></tr>
          <tr><th>Area flagged as changed</th><td>{stats.flags_total_ac.toFixed(2)} acres in {flags.length} flag(s)</td></tr>
          <tr>
            <th>Inside the 30 m buffer (KTCDA Act 2014)</th>
            <td>{(stats.buffer.change_in_buffer_ac["30"] ?? 0).toFixed(2)} acres</td>
          </tr>
        </tbody>
      </table>

      {first && last && first.season !== last.season && (
        <>
          <h2>Before and after</h2>
          <div className="grid2" style={{ gridTemplateColumns: "1fr 1fr" }}>
            {[first, last].map((s) => (
              <figure key={s.season} style={{ margin: 0 }}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={lakeUrl(id, `truecolor/${s.season}.png`)} alt={seasonLabel(s.season)} style={{ width: "100%", imageRendering: "pixelated" }} />
                <figcaption className="small">{seasonLabel(s.season)} · median of {s.clear_looks} clear looks</figcaption>
              </figure>
            ))}
          </div>
        </>
      )}

      <h2>Change flags</h2>
      <table>
        <thead>
          <tr><th>Flag</th><th>Zone</th><th>Now</th><th className="num">Acres</th><th>First seen</th><th>Status</th><th>Confidence</th><th>Centre (lat, lon)</th></tr>
        </thead>
        <tbody>
          {flags.map((f) => {
            const [lon, lat] = centroid(f.geometry);
            const p = f.properties;
            return (
              <tr key={p.flag_id}>
                <td>{p.flag_id}</td>
                <td>{p.zone}</td>
                <td>{kindLabel(p.kind)}</td>
                <td className="num">{p.area_ac.toFixed(2)}</td>
                <td>{seasonLabel(p.first_seen)}</td>
                <td>{p.status}</td>
                <td>{p.confidence}</td>
                <td>{lat.toFixed(5)}, {lon.toFixed(5)}</td>
              </tr>
            );
          })}
          {flags.length === 0 && <tr><td colSpan={8}>No lasting change detected.</td></tr>}
        </tbody>
      </table>

      <h2>Area by dry season (acres)</h2>
      <table>
        <thead>
          <tr><th>Season</th><th className="num">Water</th><th className="num">Floating veg.</th><th className="num">Bare/built</th><th className="num">Land veg. in bed</th><th className="num">Clear looks</th></tr>
        </thead>
        <tbody>
          {drySeasons(stats).map((s) => (
            <tr key={s.season}>
              <td>{seasonLabel(s.season)}</td>
              {s.status === "ok" ? (
                <>
                  <td className="num">{s.water_ac?.toFixed(2)}</td>
                  <td className="num">{s.floating_veg_ac?.toFixed(2)}</td>
                  <td className="num">{s.bare_built_ac?.toFixed(2)}</td>
                  <td className="num">{s.land_veg_ac?.toFixed(2) ?? "—"}</td>
                </>
              ) : (
                <td colSpan={4} className="muted">Not enough clear images</td>
              )}
              <td className="num">{s.clear_looks}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2>Method</h2>
      <p className="small">
        Sentinel-2 Level-2A imagery (10 m) from the Registry of Open Data on AWS, found through Earth Search. Clouds
        removed with the scene classification layer; building shadows masked. For each year, a median composite of
        January–April. Each pixel is classed as water (MNDWI above a per-lake Otsu threshold), floating vegetation
        (NDVI ≥ {stats.thresholds.veg_ndvi} inside the historical footprint with low shortwave-infrared reflectance,
        counted as lake), land vegetation, or bare/built (NDVI &lt; {stats.thresholds.bare_ndvi} and NDBI &gt;{" "}
        {stats.thresholds.ndbi}). A lake-bed pixel is flagged only if it was lake in every 2019–2020 dry season and is
        land in its latest dry seasons: bare or built, or grassed over with shortwave-infrared reflectance clearly
        above its own 2019–2020 level. Two seasons in a row is &ldquo;confirmed&rdquo;. In the 30 m buffer, only
        natural ground that turned bare or built is flagged.
        Patches under {stats.thresholds.min_flag_px} pixels ({stats.thresholds.min_flag_px * 100} m²) are dropped.
        Anyone can re-run the analysis from the scene IDs below with the open-source code.
      </p>
      <p className="small"><strong>Scenes:</strong> {Array.from(new Set(stats.seasons.flatMap((s) => s.scene_ids))).join(", ") || "—"}</p>

      <h2>Draft letters</h2>
      <p className="small muted no-print">Filled from the largest flag. Complete the parts in [square brackets] before sending.</p>
      <Letter title="Complaint to the lake custodian" text={fill(templates.complaint, letterValues(top))} />
      <Letter title="RTI application" text={fill(templates.rti, letterValues(top))} />

      <p className="small muted">
        Credits: Contains modified Copernicus Sentinel data (2019–2026). Lake outlines: ATREE-CSEI, Map of Lakes in
        Bengaluru Urban (CC BY). Data: {DATA_URL}.
      </p>
    </main>
  );
}
